# Generated by Django 5.2.2 on 2025-06-13 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_order_survey', models.BooleanField(default=True, verbose_name='Показывать опрос после первого заказа')),
                ('orders_between_surveys', models.PositiveIntegerField(default=10, verbose_name='Количество заказов между опросами')),
                ('days_between_surveys', models.PositiveIntegerField(default=30, verbose_name='Количество дней между опросами')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Настройки опросов',
                'verbose_name_plural': 'Настройки опросов',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='disable_feedback_surveys',
            field=models.BooleanField(default=False, verbose_name='Отключить опросы об удовлетворенности'),
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка пользователя',
                'verbose_name_plural': 'Оценки пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedbackStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_survey_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего опроса')),
                ('orders_since_last_survey', models.PositiveIntegerField(default=0, verbose_name='Заказов с последнего опроса')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Всего заказов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статус опросов пользователя',
                'verbose_name_plural': 'Статусы опросов пользователей',
            },
        ),
    ]
