# Generated by Django 5.2.2 on 2025-06-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_feedbacksettings_profile_disable_feedback_surveys_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackSettings',
        ),
        migrations.RemoveField(
            model_name='userfeedbackstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disable_feedback_surveys',
        ),
        migrations.DeleteModel(
            name='UserFeedback',
        ),
        migrations.DeleteModel(
            name='UserFeedbackStatus',
        ),
    ]
