# Generated by Django 5.2.2 on 2025-06-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_deliverysettings_order_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
