# Generated by Django 5.2.2 on 2025-06-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderRating',
        ),
    ]
