# Generated by Django 5.2.2 on 2025-06-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_newsslide_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsslide',
            name='title',
        ),
        migrations.RemoveField(
            model_name='newsslide',
            name='description',
        ),
    ] 