# Generated by Django 5.2.2 on 2025-06-13 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_newsslide_title_remove_newsslide_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Оцените удобство использования приложения', max_length=200, verbose_name='Заголовок опроса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание опроса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('frequency_days', models.PositiveIntegerField(default=0, help_text='0 - только после первого заказа, >0 - через указанное количество дней', verbose_name='Частота опроса (дней)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки опроса',
                'verbose_name_plural': 'Настройки опросов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на опрос',
                'verbose_name_plural': 'Ответы на опросы',
                'ordering': ['-created_at'],
            },
        ),
    ]
