# Generated by Django 5.2.2 on 2025-06-13 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_surveysettings_usersurvey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurveyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_order_survey_shown', models.BooleanField(default=False, verbose_name='Показан опрос после первого заказа')),
                ('last_survey_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего опроса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_status', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус опроса пользователя',
                'verbose_name_plural': 'Статусы опросов пользователей',
            },
        ),
    ]
