# Generated by Django 5.2.2 on 2025-06-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_usersurveystatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveySettings',
        ),
        migrations.RemoveField(
            model_name='usersurveystatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSurvey',
        ),
        migrations.DeleteModel(
            name='UserSurveyStatus',
        ),
    ]
