# Generated by Django 5.2.2 on 2025-06-13 19:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_surveysettings_remove_usersurveystatus_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Опишите, что пользователи должны оценить', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Опрос с оценкой',
                'verbose_name_plural': 'Опросы с оценкой',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID пользователя Telegram')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('rating', models.PositiveSmallIntegerField(help_text='Оценка от 1 до 5 звезд', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='home.ratingpoll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Оценка пользователя',
                'verbose_name_plural': 'Оценки пользователей',
                'ordering': ['-created_at'],
                'unique_together': {('poll', 'user_id')},
            },
        ),
    ]
