# Generated by Django 5.2.2 on 2025-06-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_ratingpoll_userrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название магазина')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_info/', verbose_name='Логотип')),
                ('description', models.TextField(help_text='Краткое описание магазина', verbose_name='Описание')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(blank=True, help_text='Например: Пн-Пт: 9:00-18:00, Сб-Вс: выходной', max_length=255, verbose_name='Часы работы')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('delivery_info', models.TextField(blank=True, verbose_name='Информация о доставке')),
                ('payment_info', models.TextField(blank=True, verbose_name='Информация об оплате')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('background_color', models.CharField(default='#f8f9fa', help_text='HEX-код цвета, например: #f8f9fa', max_length=20, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#212529', help_text='HEX-код цвета, например: #212529', max_length=20, verbose_name='Цвет текста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Информация о магазине',
                'verbose_name_plural': 'Информация о магазине',
            },
        ),
    ]
