# Generated by Django 5.2.2 on 2025-06-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_shopinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopinfo',
            name='delivery_info',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='payment_info',
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='vk',
            field=models.CharField(blank=True, max_length=100, verbose_name='VK'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='description',
            field=models.TextField(verbose_name='Описание магазина'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='working_hours',
            field=models.TextField(blank=True, verbose_name='Часы работы'),
        ),
    ]
