# Generated by Django 5.2.2 on 2025-06-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_shopinfo_delivery_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopinfo',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='text_color',
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='address',
            field=models.TextField(blank=True, max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='description',
            field=models.TextField(help_text='Краткое описание магазина (до 200 символов)', max_length=200, verbose_name='Описание магазина'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='instagram',
            field=models.CharField(blank=True, help_text='Имя пользователя без @', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='telegram',
            field=models.CharField(blank=True, help_text='Имя пользователя без @', max_length=100, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='vk',
            field=models.CharField(blank=True, help_text='ID или короткое имя', max_length=100, verbose_name='VK'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Номер телефона в международном формате', max_length=100, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='working_hours',
            field=models.TextField(blank=True, max_length=100, verbose_name='Часы работы'),
        ),
    ]
