# Generated by Django 5.2.2 on 2025-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступна'),
        ),
        migrations.AddField(
            model_name='section',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
    ]
