# Generated by Django 5.2.2 on 2025-06-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_available_section_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
    ]
